name: Send Facebook post

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Sending Facebook post
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/send-fb-post-with-media'
    strategy:
      matrix:
        include:
          - python-version: "3.10"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Testing script
        env:
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          STATUS_TEXT: ${{ secrets.STATUS_TEXT }}
          STATUS_IMAGE_URL_1: ${{ secrets.STATUS_IMAGE_URL_1 }}
          STATUS_IMAGE_URL_2: ${{ secrets.STATUS_IMAGE_URL_2 }}
          STATUS_IMAGE_URL_3: ${{ secrets.STATUS_IMAGE_URL_3 }}
          STATUS_IMAGE_URL_4: ${{ secrets.STATUS_IMAGE_URL_4 }}
        run: python3 test.py
